smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -327,18 +327,50 @@ jobs:
             unzip awscliv2.zip
             sudo ./aws/install
       - run:
-          name: Get backend url
+          name: Install node modules
           command: |
-            # your code here
+            cd backend
+            npm install
+      - attach_workspace:
+          at: ~/
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
+            pwd
+            echo " --- Cat inventory file --- "            
+            export BACKEND_IP=$(cat ~/project/.circleci/ansible/inventory.txt | sed 1d)
+            echo "The BACKEND IP: ${BACKEND_IP}"
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "The API URL: ${API_URL}"
+            sleep 60
+            curl "${API_URL}/api/status"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                exit 0
+            else
+                exit 1
+            fi            
       - run:
           name: Frontend smoke test.
           command: |
+           
             # your code here
-      # Here's where you will add some code to rollback on failure  
+            echo ${CIRCLE_WORKFLOW_ID:0:7}
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+                exit 0
+            else
+                exit 1
+            fi
+      # Here's where you will add some code to rollback on failure
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - destroy-environment
+
+  
 
 
       
@@ -370,5 +402,7 @@ workflows:
       - deploy-frontend:
           requires: [run-migrations] 
       - deploy-backend:
-          requires: [run-migrations]   
+          requires: [run-migrations]  
+      - smoke-test:
+          requires: [deploy-frontend,deploy-backend] 
     
